import pandas as pd

def sales_summary_statistics(sales_data):
    """
    Generate summary statistics for sales data, including total revenue, unique customers, 
    average order value, top-selling products by quantity and revenue, and average revenue 
    per customer.

    Args:
        sales_data (pandas.DataFrame): A DataFrame containing sales data with at least 
                                       the following columns: 'Quantity', 'UnitPrice', 
                                       'CustomerID', 'InvoiceNo', and 'Description'. 

    Returns:
        pandas.DataFrame: A DataFrame containing the calculated summary statistics. If 
                          no sales data is provided, returns an empty DataFrame.

    The function computes the following statistics:
    - 'total_revenue': The total revenue generated by all sales.
    - 'unique_customers': The number of unique customers.
    - 'average_order_value': The average value of an order (sum of revenue per invoice).
    - 'top_selling_product_quantity': The product with the highest quantity sold.
    - 'top_selling_product_revenue': The product with the highest total revenue.
    - 'average_revenue_per_customer': The average revenue generated by each customer.

    Example:
        import pandas as pd

        # Example sales data
        sales_data = pd.DataFrame({
            'Quantity': [10, 5, 3, 15],
            'UnitPrice': [100, 200, 150, 100],
            'CustomerID': [1, 2, 1, 3],
            'InvoiceNo': ['INV001', 'INV002', 'INV003', 'INV004'],
            'Description': ['Product A', 'Product B', 'Product A', 'Product C']
        })

        # Get sales summary statistics
        summary = sales_summary_statistics(sales_data)
        print(summary)

    Output:
        total_revenue                   2750.0
        unique_customers                 3
        average_order_value             915.0
        top_selling_product_quantity    Product A
        top_selling_product_revenue     Product A
        average_revenue_per_customer    916.666667
    """
    
    if len(sales_data.index) == 0:
        return pd.DataFrame({})
    
    # Get summary variables
    sales_data['Revenue'] = sales_data['Quantity'] * sales_data['UnitPrice']

    unique_customers = sales_data['CustomerID'].nunique()

    total_revenue = (sales_data['Quantity'] * sales_data['UnitPrice']).sum()

    top_selling_product_quantity = sales_data.groupby('Description')['Quantity'].sum().idxmax()

    average_order_value = sales_data.groupby('InvoiceNo')['Revenue'].sum().mean()
    
    top_selling_product_revenue = sales_data.groupby('Description')['Revenue'].sum().idxmax()

    revenue_per_customer = sales_data.groupby('CustomerID')['Revenue'].sum()
    average_revenue_per_customer = revenue_per_customer.mean()
    
    summary = {
        'total_revenue': [total_revenue],
        'unique_customers': [unique_customers],
        'average_order_value': [average_order_value],
        'top_selling_product_quantity': [top_selling_product_quantity],
        'top_selling_product_revenue': [top_selling_product_revenue],
        'average_revenue_per_customer': [average_revenue_per_customer]
    }

    return pd.DataFrame(summary)